local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "frFR")
if not L then return end

L["Bindings"] = "Raccourcis"
L["This input already exists for this binding."] = "Cette touche existe déjà pour ce raccourci."
L["This input conflicts with"] = "Cette touche est en conflit avec"
L["Cannot remove; Binding must have at least one input."] = "Suppression impossible ; le raccourci doit avoir au moins une touche."
L["Cannot replace this binding as it requires at least one input."] = "Impossible de remplacer ce raccourci, il lui faut au moins une touche."

L["Up"] = "Haut"
L["Down"] = "Bas"
L["Left"] = "Gauche"
L["Right"] = "Droite"
L["Left Click"] = "Clic gauche"
L["Right Click"] = "Clic droit"
L["Jump to Beginning"] = "Aller au début"
L["Jump to End"] = "Aller à la fin"
L["Drag"] = "Glisser"
L["Next"] = "Suivant"
L["Previous"] = "Précédent"
L["Next Window"] = "Fenêtre suivante"
L["Previous Window"] = "Fenêtre précédente"
L["Read Tooltip"] = "Lire l'infobulle"
L["Context Menu"] = "Menu contextuel"
L["Previous Tooltip Line"] = "Ligne d'infobulle précédente"
L["Next Tooltip Line"] = "Ligne d'infobulle suivante"
L["Read Tooltip Left"] = "Lire l'infobulle à gauche"
L["Read Tooltip Right"] = "Lire l'infobulle à droite"
L["Destroy Cursor Item"] = "Détruire l'objet du curseur"

L["Previous Buffer Item"] = "Élément précédent du tampon"
L["Next Buffer Item"] = "Élément suivant du tampon"
L["Previous Buffer"] = "Tampon précédent"
L["Next Buffer"] = "Tampon suivant"
L["Action Bars"] = "Barres d'action"
L["Roll Tooltip"] = "Infobulle du jet"
L["Roll Need"] = "Jet Besoin"
L["Roll Greed"] = "Jet Cupidité"
L["Roll Pass"] = "Passer"
L["Roll Bonus"] = "Jet bonus"
L["Scroll Up"] = "Défiler vers le haut"
L["Scroll Down"] = "Défiler vers le bas"
