local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "frFR")
if not L then return end

L["Navigation"] = "Navigation"
L["Auto-move to Interact Target"] = "Aller automatiquement à la cible d'interaction"

--Compass
L["Compass"] = "Boussole"
L["Speak Compass Direction"] = "Annoncer la direction de la boussole"
L["north"] = "nord"
L["northeast"] = "nord-est"
L["east"] = "est"
L["southeast"] = "sud-est"
L["south"] = "sud"
L["southwest"] = "sud-ouest"
L["west"] = "ouest"
L["northwest"] = "nord-ouest"
L["Outdoors Alert"] = "Alerte extérieur"
L["Indoors Alert"] = "Alerte intérieur"
L["outdoors"] = "dehors"
L["indoors"] = "à l'intérieur"
L["Flying Started Alert"] = "Alerte début de vol"
L["Flying Ended Alert"] = "Alerte fin de vol"
L["flying"] = "en vol"
L["flying ended"] = "vol terminé"
L["Swimming Alert"] = "Alerte nage"
L["swimming"] = "nage"
L["Diving Alert"] = "Alerte plongée"
L["diving"] = "plongée"

--Follow
L["Follow"] = "Suivre"
L["Play Sound on Follow or Unfollow"] = "Jouer un son au début ou à la fin du suivi"

--Maps
L["Maps"] = "Cartes"
L["Zone Changed Alert"] = "Alerte changement de zone"
L["Subzone Changed Alert"] = "Alerte changement de sous-zone"
L["Beacon"] = "Balise"
L["Beacon Sound"] = "Son de la balise"
L["Beacon Aligned"] = "Balise alignée"
L["Beacon Off Course"] = "Balise hors trajectoire"
L["Waypoint Reached"] = "Point de passage atteint"

--Atlas
L["Atlas"] = "Atlas"
L["Key"] = "Clé"
L["Game Version"] = "Version du jeu"
L["Position unavailable"] = "Position indisponible"
L["No route found"] = "Aucun itinéraire trouvé"
L["Arrived"] = "Arrivé"
L["waypoints"] = "points de passage"
L["yards"] = "mètres"
L["Beacon set"] = "Balise placée"
L["Beacon stopped"] = "Balise arrêtée"
L["Entry Points"] = "Points d'entrée"
L["Destinations"] = "Destinations"
L["ahead"] = "devant"
L["behind"] = "derrière"
L["left"] = "à gauche"
L["right"] = "à droite"
L["Wall Detection"] = "Détection des murs"
L["Blocked"] = "Bloqué"
L["Mostly Blocked"] = "Presque bloqué"
L["Impeded"] = "Gêné"
L["Slowed"] = "Ralenti"
L["Slightly Slowed"] = "Légèrement ralenti"
L["Fall Detection"] = "Détection des chutes"
L["Falling"] = "Chute"
L["Falling Sound"] = "Son de chute"
L["Falling Announcement"] = "Annonce de chute"
L["Ignore Jumps"] = "Ignorer les sauts"
L["Delay (milliseconds)"] = "Délai (millisecondes)"
L["Turn to Waypoint"] = "Se tourner vers le point de passage"
L["Turning is not available here"] = "Impossible de se tourner ici"
L["Pitch Lock"] = "Verrouillage de l'inclinaison"
L["WowVision set the camera to always follow behind your character, which turning to waypoints needs. You can change the camera following style in the game options under Controls."] = "WowVision a réglé la caméra pour toujours suivre derrière votre personnage, ce qui est nécessaire pour se tourner vers les points de passage. Vous pouvez changer le style de suivi de la caméra dans les options du jeu, sous Commandes."
L["No active waypoint"] = "Aucun point de passage actif"
L["Next Waypoint"] = "Point de passage suivant"
L["Previous Waypoint"] = "Point de passage précédent"
L["remaining"] = "restants"
L["End of route"] = "Fin de l'itinéraire"
L["Start of route"] = "Début de l'itinéraire"
L["last %d yards direct"] = "%d derniers mètres en ligne droite"
L["Arrival Distance"] = "Distance d'arrivée"
L["Cycle Arrival Distance"] = "Changer la distance d'arrivée"
L["Cancel Navigation"] = "Annuler la navigation"
L["Short Range"] = "Courte portée"
L["Medium Range"] = "Moyenne portée"
L["Long Range"] = "Longue portée"
L["Arrival Radius"] = "Rayon d'arrivée"
