local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "frFR")
if not L then return end

-- Quests module (Questie-backed quest data)
L["Nearby Level Range"] = "Écart de niveau à proximité"
L["Include Repeatable Quests"] = "Inclure les quêtes répétables"
L["Questie is not loaded"] = "Questie n'est pas chargé"
L["Questie is still loading"] = "Questie est encore en cours de chargement"
L["No nearby quests"] = "Aucune quête à proximité"
L["No quests in progress"] = "Aucune quête en cours"
L["No targets"] = "Aucune cible"
L["far"] = "loin"
L["from"] = "de"
L["target"] = "cible"
L["Level"] = "Niveau"
L["Unknown"] = "Inconnu"

-- Scanner categories from quest and NPC data
L["NPCs"] = "PNJ"
L["Nearby"] = "À proximité"
L["In Progress"] = "En cours"
L["Quest Givers"] = "Donneurs de quêtes"
L["Vendors"] = "Marchands"
L["Trainers"] = "Maîtres"
L["Class Trainers"] = "Maîtres de classe"
L["Flight Masters"] = "Maîtres de vol"
L["Innkeepers"] = "Aubergistes"
L["Bankers"] = "Banquiers"
L["Auctioneers"] = "Commissaires-priseurs"
L["Stable Masters"] = "Maîtres des écuries"
L["Battlemasters"] = "Maîtres de guerre"
L["Spirit Healers"] = "Gardiens des âmes"
L["Mailboxes"] = "Boîtes aux lettres"
L["Rares"] = "Rares"
L["Start"] = "Début"
L["Turn In"] = "Rendre"
L["Objectives"] = "Objectifs"
L["quests"] = "quêtes"
L["spawns"] = "apparitions"
L["Loading"] = "Chargement"
L["near"] = "près de"
L["Repeatable"] = "Répétable"
L["phased out"] = "hors phase"
L["No quest data source"] = "Aucune source de données de quêtes"
L["Quest Giver"] = "Donneur de quête"
L["seen"] = "vu"

-- Quest areas (the shaded objective areas of tracked quests)
L["Quest Area Alert"] = "Alerte de zone de quête"
L["Entering area"] = "Entrée dans la zone"
L["Leaving area"] = "Sortie de la zone"
