local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "frFR")
if not L then return end

L["Targeting"] = "Ciblage"
L["Hard Target"] = "Cible principale"
L["Announce Hard Target"] = "Annoncer la cible principale"
L["Target Change"] = "Changement de cible"
L["Health Monitor"] = "Moniteur de vie"
L["Announce Raid Target Marker on Hard Target"] = "Annoncer le marqueur de raid de la cible principale"
L["Star"] = "Étoile"
L["Circle"] = "Cercle"
L["Diamond"] = "Losange"
L["Triangle"] = "Triangle"
L["Moon"] = "Lune"
L["Square"] = "Carré"
L["X"] = "Croix"
L["Skull"] = "Crâne"

--Soft Targeting
L["Soft Target Enemy"] = "Ciblage doux ennemi"
L["Soft Target Friend"] = "Ciblage doux allié"
L["Soft Target Interact"] = "Ciblage doux d'interaction"
L["Target in Combat Sound"] = "Son de cible en combat"
L["Soft Target Enemy Arc"] = "Arc du ciblage doux ennemi"
L["Soft Target Enemy Range"] = "Portée du ciblage doux ennemi"
L["Soft Target Friend Arc"] = "Arc du ciblage doux allié"
L["Soft Target Friend Range"] = "Portée du ciblage doux allié"
L["Soft Target Interact Arc"] = "Arc du ciblage doux d'interaction"
L["Soft Target Interact Range"] = "Portée du ciblage doux d'interaction"
L["Directly in Front"] = "Juste devant"
L["15 Degrees in Front"] = "15 degrés devant"
L["180 Degrees in Front"] = "180 degrés devant"
L["Soft Targeting With a Hard Target"] = "Ciblage doux avec une cible principale"
L["Only Without an Attackable Hard Target"] = "Seulement sans cible principale attaquable"
L["Only Without a Hard Target"] = "Seulement sans cible principale"
L["Always"] = "Toujours"
L["Make Soft Target the Hard Target"] = "Faire de la cible douce la cible principale"
L["Off"] = "Désactivé"
L["Enemies"] = "Ennemis"
L["Friends"] = "Alliés"
L["after combat"] = "après le combat"
L["not available"] = "indisponible"
L["default"] = "par défaut"

L["Virtual Focus"] = "Focalisation virtuelle"
L["Target Focus"] = "Cibler la focalisation"
L["Game Default"] = "Réglage du jeu"
