local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "frFR")
if not L then return end

L["WowVision"] = "WowVision"
L["UI"] = "Interface"
L["Interrupt Speech on Window Close"] = "Interrompre la parole à la fermeture d'une fenêtre"

--Combat
L["Combat"] = "Combat"
L["Combat Started Alert"] = "Alerte début de combat"
L["Combat Ended Alert"] = "Alerte fin de combat"
L["combat started"] = "combat commencé"
L["combat ended"] = "combat terminé"

L["Game Menu"] = "Menu du jeu"
L["Windows"] = "Fenêtres"

--UI names
L["Button"] = "Bouton"
L["Checkbox"] = "Case à cocher"
L["Dropdown"] = "Liste déroulante"
L["EditBox"] = "Champ de saisie"
L["Separator"] = "Séparateur"
L["Text"] = "Texte"
L["ProxyButton"] = "Bouton"
L["ProxyCheckButton"] = "Case à cocher"
L["ProxyDropdownButton"] = "Liste déroulante"
L["ProxyEditBox"] = "Champ de saisie"

L["Panel"] = "Panneau"
L["List"] = "Liste"
L["Bar"] = "Barre"

--Common UI phrases
L["Tabs"] = "Onglets"
L["Side Tabs"] = "Onglets latéraux"
L["selected"] = "sélectionné"
L["Checked"] = "Coché"
L["Unchecked"] = "Non coché"
L["Disable"] = "Désactiver"
L["Disabled"] = "Désactivé"
L["Enable"] = "Activer"
L["Enabled"] = "Activé"
L["Menu"] = "Menu"
L["Context Menu"] = "Menu contextuel"
L["Left Click"] = "Clic gauche"
L["Drag"] = "Glisser"
L["Available"] = "Disponible"
L["Unavailable"] = "Indisponible"
L["Collapsed"] = "Replié"
L["Expanded"] = "Déplié"
L["Expand/Collapse"] = "Déplier/replier"
L["Known"] = "Connu"
L["Search"] = "Rechercher"
L["Clear"] = "Effacer"
L["Results"] = "Résultats"
L["Categories"] = "Catégories"
L["Page"] = "Page"
L["Previous Page"] = "Page précédente"
L["Next Page"] = "Page suivante"
L["Add"] = "Ajouter"
L["Remove"] = "Retirer"
L["Unlearn"] = "Désapprendre"

L["Empty"] = "Vide"
L["Not implemented yet"] = "Pas encore implémenté"
L["None"] = "Aucun"
L["Type"] = "Type"
L["Select Type"] = "Choisir le type"
L["Power Type"] = "Type de puissance"
L["Unit"] = "Unité"
L["Instance ID"] = "ID d'instance"
L["Parameters"] = "Paramètres"
L["Items"] = "Objets"
L["Options"] = "Options"
L["Scroll Up"] = "Défiler vers le haut"
L["Scroll Down"] = "Défiler vers le bas"
L["Minimum"] = "Minimum"
L["Maximum"] = "Maximum"
L["in stock"] = "en stock"
L["Gold"] = "Or"
L["Silver"] = "Argent"
L["Copper"] = "Cuivre"
L["Price"] = "Prix"
L["Quantity"] = "Quantité"
L["Place Item Here"] = "Placer l'objet ici"
L["Repair"] = "Réparer"
L["Replace"] = "Remplacer"
L["Replace?"] = "Remplacer ?"
L["Voice Pack"] = "Pack de voix"
L["Socketing"] = "Sertissage"
L["Interact"] = "Interagir"
L["Close"] = "Fermer"
L["Goodbye"] = "Au revoir"
L["Available Quest"] = "Quête disponible"
L["Accepted Quest"] = "Quête acceptée"
L["Details"] = "Détails"
L["Progress"] = "Progression"
L["Rewards"] = "Récompenses"

L["Objectives"] = "Objectifs"
L["Complete"] = "Terminée"
L["Failed"] = "Échouée"

L["Spells"] = "Sorts"
L["Spell Flyout"] = "Menu de sorts"
L["Enchant"] = "Enchanter"
L["Trade"] = "Échange"

--Colors
L["Red"] = "Rouge"
L["Orange"] = "Orange"
L["Yellow"] = "Jaune"
L["Green"] = "Vert"
L["Blue"] = "Bleu"
L["Grey"] = "Gris"
L["White"] = "Blanc"
L["Purple"] = "Violet"
L["Light Gold"] = "Or clair"
L["Light Blue"] = "Bleu clair"
L["Meta"] = "Méta"
L["Prismatic"] = "Prismatique"
L["Reward"] = "Récompense"

--Character frame
L["Equipment"] = "Équipement"
L["Stats"] = "Caractéristiques"
L["Resistances"] = "Résistances"
L["Mounted"] = "Sur une monture"

--Equipment slot names (for empty slots)
L["Ammo"] = "Munitions"
L["Head"] = "Tête"
L["Neck"] = "Cou"
L["Shoulders"] = "Épaules"
L["Back"] = "Dos"
L["Chest"] = "Torse"
L["Shirt"] = "Chemise"
L["Tabard"] = "Tabard"
L["Wrist"] = "Poignets"
L["Hands"] = "Mains"
L["Waist"] = "Taille"
L["Legs"] = "Jambes"
L["Feet"] = "Pieds"
L["Finger"] = "Doigt"
L["Trinket"] = "Bijou"
L["Main Hand"] = "Main droite"
L["Off Hand"] = "Main gauche"
L["Ranged"] = "À distance"

--Talents
L["Talents"] = "Talents"
L["Specializations"] = "Spécialisations"
L["Specialization Info"] = "Infos de spécialisation"
L["Glyphs"] = "Glyphes"

--Object field labels
L["Current"] = "Actuel"
L["Label"] = "Libellé"
L["Percent"] = "Pourcentage"
L["Formatted"] = "Formaté"
L["Active"] = "Actif"
L["Status"] = "État"
L["Name"] = "Nom"

--Aura field labels
L["Applications"] = "Cumuls"
L["Aura Instance ID"] = "ID d'instance de l'aura"
L["Can Apply Aura"] = "Peut appliquer l'aura"
L["Charges"] = "Charges"
L["Dispel Type"] = "Type de dissipation"
L["Curse"] = "Malédiction"
L["Disease"] = "Maladie"
L["Magic"] = "Magie"
L["Poison"] = "Poison"
L["Enrage"] = "Enrager"
L["Duration"] = "Durée"
L["Expiration Time"] = "Heure d'expiration"
L["Remaining Duration"] = "Durée restante"
L["Icon"] = "Icône"
L["Is Boss Aura"] = "Est une aura de boss"
L["Is From Player Or Pet"] = "Vient du joueur ou du familier"
L["Is Harmful"] = "Est nocive"
L["Is Helpful"] = "Est bénéfique"
L["Is Nameplate Only"] = "Seulement sur la barre de nom"
L["Is Raid"] = "Est de raid"
L["Is Stealable"] = "Peut être volée"
L["Max Charges"] = "Charges max"
L["Nameplate Show All"] = "Barre de nom : tout afficher"
L["Nameplate Show Personal"] = "Barre de nom : afficher le personnel"
L["Points"] = "Points"
L["Source Unit"] = "Unité source"
L["Spell ID"] = "ID du sort"
L["Time Mod"] = "Modificateur de temps"

--Buffer labels
L["Objects"] = "Objets"
L["Object"] = "Objet"
L["Source"] = "Source"
L["New Buffer"] = "Nouveau tampon"
L["New"] = "Nouveau"
L["Select Buffer Type"] = "Choisir le type de tampon"
L["Buffer Not Found"] = "Tampon introuvable"
L["Buffer Group"] = "Groupe de tampons"
L["No object configured"] = "Aucun objet configuré"
L["Empty Object"] = "Objet vide"
L["Template"] = "Modèle"
L["Custom"] = "Personnalisé"
L["Format"] = "Format"
L["Default"] = "Par défaut"
L["Save"] = "Enregistrer"
L["Invalid parameters"] = "Paramètres non valides"
L["Parameters must identify a single object"] = "Les paramètres doivent désigner un seul objet"

--Time
L["day"] = "jour"
L["days"] = "jours"
L["hour"] = "heure"
L["hours"] = "heures"
L["minute"] = "minute"
L["minutes"] = "minutes"
L["second"] = "seconde"
L["seconds"] = "secondes"
L["Number"] = "Nombre"
L["Radio"] = "Bouton radio"
L["Scope"] = "Portée"
L["Global"] = "Global"
