local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "deDE")
if not L then return end

L["Auction House"] = "Auktionshaus"
L["Auctions"] = "Auktionen"
L["Buyout Frame"] = "Sofortkauf-Fenster"
L["Bid Frame"] = "Gebot-Fenster"

L["Unit Price"] = "Stückpreis"
L["Buyout Price"] = "Sofortkaufpreis"
L["Bid Price"] = "Gebotspreis"
L["Seller"] = "Verkäufer"
L["Sold"] = "Verkauft"
L["Bids"] = "Gebote"
L["Bid Amount"] = "Gebotsbetrag"
L["Minimum Bid"] = "Mindestgebot"
L["Bidder"] = "Bieter"
L["Time Left"] = "Verbleibende Zeit"
L["Short"] = "Kurz"
L["Medium"] = "Mittel"
L["Long"] = "Lang"
L["Very Long"] = "Sehr lang"

-- TBC auction house
L["Categories"] = "Kategorien"
L["Results"] = "Ergebnisse"
L["Current Bid"] = "Aktuelles Gebot"
L["Buyout"] = "Sofortkauf"
L["Starting Bid"] = "Anfangsgebot"
L["No Bids"] = "Keine Gebote"
L["Deposit"] = "Einlage"
L["Create Auction"] = "Auktion erstellen"
L["Place Item"] = "Gegenstand platzieren"
L["Stack Size"] = "Stapelgröße"
L["Number of Stacks"] = "Anzahl der Stapel"
L["Filters"] = "Filter"
L["Minimum Level"] = "Mindeststufe"
L["Maximum Level"] = "Höchststufe"
L["Quantity"] = "Menge"
L["Available"] = "Verfügbar"
L["Rarity"] = "Seltenheit"
L["Sort"] = "Sortieren"
L["Price Options"] = "Preisoptionen"
L["Your Gold"] = "Dein Gold"
L["Duration"] = "Dauer"
L["12 Hours"] = "12 Stunden"
L["24 Hours"] = "24 Stunden"
L["48 Hours"] = "48 Stunden"
L["Previous Page"] = "Vorherige Seite"
L["Next Page"] = "Nächste Seite"
L["Item Selected"] = "Gegenstand ausgewählt"
L["Selected"] = "Ausgewählt"

L["Min Stack Size"] = "Mindeststapelgröße"
L["No Results"] = "Keine Ergebnisse"
