local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "deDE")
if not L then return end

L["Bindings"] = "Tastenbelegung"
L["This input already exists for this binding."] = "Diese Eingabe existiert bereits für diese Belegung."
L["This input conflicts with"] = "Diese Eingabe steht in Konflikt mit"
L["Cannot remove; Binding must have at least one input."] = "Entfernen nicht möglich; Belegung muss mindestens eine Eingabe haben."
L["Cannot replace this binding as it requires at least one input."] = "Diese Belegung kann nicht ersetzt werden, da mindestens eine Eingabe erforderlich ist."

L["Up"] = "Hoch"
L["Down"] = "Runter"
L["Left"] = "Links"
L["Right"] = "Rechts"
L["Left Click"] = "Linksklick"
L["Right Click"] = "Rechtsklick"
L["Jump to Beginning"] = "Zum Anfang springen"
L["Jump to End"] = "Zum Ende springen"
L["Drag"] = "Ziehen"
L["Next"] = "Weiter"
L["Previous"] = "Zurück"
L["Next Window"] = "Nächstes Fenster"
L["Previous Window"] = "Vorheriges Fenster"
L["Read Tooltip"] = "Tooltip vorlesen"
L["Context Menu"] = "Kontextmenü"
L["Previous Tooltip Line"] = "Vorherige Tooltipzeile"
L["Next Tooltip Line"] = "Nächste Tooltipzeile"
L["Read Tooltip Left"] = "Tooltip links vorlesen"
L["Read Tooltip Right"] = "Tooltip rechts vorlesen"
L["Destroy Cursor Item"] = "Cursorgegenstand zerstören"

L["Previous Buffer Item"] = "Vorheriges Pufferelement"
L["Next Buffer Item"] = "Nächstes Pufferelement"
L["Previous Buffer"] = "Vorheriger Puffer"
L["Next Buffer"] = "Nächster Puffer"
L["Action Bars"] = "Aktionsleisten"
L["Roll Tooltip"] = "Würfel-Tooltip"
L["Roll Need"] = "Bedarf würfeln"
L["Roll Greed"] = "Gier würfeln"
L["Roll Pass"] = "Passen"
L["Roll Bonus"] = "Bonuswurf"
L["Scroll Up"] = "Nach oben scrollen"
L["Scroll Down"] = "Nach unten scrollen"
