local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "deDE")
if not L then return end

L["Navigation"] = "Navigation"
L["Auto-move to Interact Target"] = "Automatisch zum Interaktionsziel bewegen"

--Compass
L["Compass"] = "Kompass"
L["Speak Compass Direction"] = "Kompassrichtung ansagen"
L["north"] = "Norden"
L["northeast"] = "Nordosten"
L["east"] = "Osten"
L["southeast"] = "Südosten"
L["south"] = "Süden"
L["southwest"] = "Südwesten"
L["west"] = "Westen"
L["northwest"] = "Nordwesten"
L["Outdoors Alert"] = "Draußen-Alarm"
L["Indoors Alert"] = "Drinnen-Alarm"
L["outdoors"] = "draußen"
L["indoors"] = "drinnen"
L["Flying Started Alert"] = "Flug-gestartet-Alarm"
L["Flying Ended Alert"] = "Flug-beendet-Alarm"
L["flying"] = "fliegen"
L["flying ended"] = "Flug beendet"
L["Swimming Alert"] = "Schwimm-Alarm"
L["swimming"] = "schwimmen"
L["Diving Alert"] = "Tauch-Alarm"
L["diving"] = "tauchen"

--Follow
L["Follow"] = "Folgen"
L["Play Sound on Follow or Unfollow"] = "Sound bei Folgen oder Entfolgen abspielen"

--Maps
L["Maps"] = "Karten"
L["Zone Changed Alert"] = "Gebietsänderungs-Alarm"
L["Subzone Changed Alert"] = "Untergebietsänderungs-Alarm"
L["Position unavailable"] = "Position nicht verfügbar"
L["No route found"] = "Keine Route gefunden"
L["Arrived"] = "Angekommen"
L["waypoints"] = "Wegpunkte"
L["yards"] = "Meter"
L["Beacon set"] = "Leuchtfeuer gesetzt"
L["Beacon stopped"] = "Leuchtfeuer gestoppt"
L["Entry Points"] = "Einstiegspunkte"
L["Destinations"] = "Ziele"
L["ahead"] = "voraus"
L["behind"] = "hinten"
L["left"] = "links"
L["right"] = "rechts"
L["Wall Detection"] = "Wanderkennung"
L["Blocked"] = "Blockiert"
L["Mostly Blocked"] = "Größtenteils blockiert"
L["Impeded"] = "Behindert"
L["Slowed"] = "Verlangsamt"
L["Slightly Slowed"] = "Leicht verlangsamt"
