local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "deDE")
if not L then return end

-- Quests module (Questie-backed quest data)
L["Nearby Level Range"] = "Stufenbereich für Quests in der Nähe"
L["Include Repeatable Quests"] = "Wiederholbare Quests einbeziehen"
L["Questie is not loaded"] = "Questie ist nicht geladen"
L["Questie is still loading"] = "Questie lädt noch"
L["No nearby quests"] = "Keine Quests in der Nähe"
L["No quests in progress"] = "Keine laufenden Quests"
L["No targets"] = "Keine Ziele"
L["far"] = "weit weg"
L["from"] = "von"
L["target"] = "Ziel"
L["Level"] = "Stufe"
L["Unknown"] = "Unbekannt"

-- Scanner categories from quest and NPC data
L["NPCs"] = "NPCs"
L["Nearby"] = "In der Nähe"
L["In Progress"] = "Laufend"
L["Quest Givers"] = "Questgeber"
L["Vendors"] = "Händler"
L["Trainers"] = "Lehrer"
L["Class Trainers"] = "Klassenlehrer"
L["Flight Masters"] = "Flugmeister"
L["Innkeepers"] = "Gastwirte"
L["Bankers"] = "Bankiers"
L["Auctioneers"] = "Auktionatoren"
L["Stable Masters"] = "Stallmeister"
L["Battlemasters"] = "Kampfmeister"
L["Spirit Healers"] = "Geistheiler"
L["Mailboxes"] = "Briefkästen"
L["Rares"] = "Seltene Gegner"
L["Start"] = "Annahme"
L["Turn In"] = "Abgabe"
L["quests"] = "Quests"
L["spawns"] = "Fundorte"
L["Loading"] = "Lädt"
L["near"] = "bei"
L["Repeatable"] = "Wiederholbar"
L["phased out"] = "ausgephast"
L["No quest data source"] = "Keine Questdatenquelle"
L["Quest Giver"] = "Questgeber"

-- Quest areas (the shaded objective areas of tracked quests)
L["Quest Area Alert"] = "Questgebiet"
L["Entering area"] = "Betrete Gebiet"
L["Leaving area"] = "Verlasse Gebiet"
