local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "deDE")
if not L then return end

L["Targeting"] = "Zielerfassung"
L["Hard Target"] = "Festes Ziel"
L["Announce Hard Target"] = "Festes Ziel ansagen"
L["Target Change"] = "Zielwechsel"
L["Health Monitor"] = "Lebensüberwachung"
L["Announce Raid Target Marker on Hard Target"] = "Schlachtzugmarkierung bei festem Ziel ansagen"
L["Star"] = "Stern"
L["Circle"] = "Kreis"
L["Diamond"] = "Diamant"
L["Triangle"] = "Dreieck"
L["Moon"] = "Mond"
L["Square"] = "Quadrat"
L["X"] = "X"
L["Skull"] = "Totenkopf"

--Soft Targeting
L["Soft Target Enemy"] = "Weiches Ziel Feind"
L["Soft Target Friend"] = "Weiches Ziel Freund"
L["Soft Target Interact"] = "Weiches Ziel Interaktion"
L["Target in Combat Sound"] = "Ziel-im-Kampf-Sound"
L["Soft Target Enemy Arc"] = "Weiches Ziel Feind: Winkel"
L["Soft Target Enemy Range"] = "Weiches Ziel Feind: Reichweite"
L["Soft Target Friend Arc"] = "Weiches Ziel Freund: Winkel"
L["Soft Target Friend Range"] = "Weiches Ziel Freund: Reichweite"
L["Soft Target Interact Arc"] = "Weiches Ziel Interaktion: Winkel"
L["Soft Target Interact Range"] = "Weiches Ziel Interaktion: Reichweite"
L["Directly in Front"] = "Direkt vor dir"
L["15 Degrees in Front"] = "15 Grad vor dir"
L["180 Degrees in Front"] = "180 Grad vor dir"
L["Soft Targeting With a Hard Target"] = "Weiches Ziel bei festem Ziel"
L["Only Without an Attackable Hard Target"] = "Nur ohne angreifbares festes Ziel"
L["Only Without a Hard Target"] = "Nur ohne festes Ziel"
L["Always"] = "Immer"
L["Make Soft Target the Hard Target"] = "Weiches Ziel wird festes Ziel"
L["Off"] = "Aus"
L["Enemies"] = "Feinde"
L["Friends"] = "Freunde"
L["after combat"] = "nach dem Kampf"
L["not available"] = "nicht verfügbar"
L["default"] = "Standard"

L["Virtual Focus"] = "Virtueller Fokus"
L["Target Focus"] = "Zielfokus"
L["Game Default"] = "Spielstandard"
