local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "deDE")
if not L then return end

L["WowVision"] = "WowVision"
L["UI"] = "Benutzeroberfläche"
L["Interrupt Speech on Window Close"] = "Sprache beim Schließen des Fensters unterbrechen"

--Combat
L["Combat"] = "Kampf"
L["Combat Started Alert"] = "Kampf-gestartet-Alarm"
L["Combat Ended Alert"] = "Kampf-beendet-Alarm"
L["combat started"] = "Kampf begonnen"
L["combat ended"] = "Kampf beendet"

L["Game Menu"] = "Spielmenü"
L["Windows"] = "Fenster"

--UI names
L["Button"] = "Schalter"
L["Checkbox"] = "Kontrollkästchen"
L["Dropdown"] = "Dropdown"
L["EditBox"] = "Eingabefeld"
L["Separator"] = "Trennlinie"
L["Text"] = "Text"
L["ProxyButton"] = "Schalter"
L["ProxyCheckButton"] = "Kontrollkästchen"
L["ProxyDropdownButton"] = "Dropdown"
L["ProxyEditBox"] = "Eingabefeld"

L["Panel"] = "Feld"
L["List"] = "Liste"
L["Bar"] = "Leiste"

--Common UI phrases
L["Tabs"] = "Reiter"
L["Side Tabs"] = "Seitenreiter"
L["selected"] = "ausgewählt"
L["Checked"] = "Aktiviert"
L["Unchecked"] = "Deaktiviert"
L["Disable"] = "Deaktivieren"
L["Disabled"] = "Deaktiviert"
L["Enable"] = "Aktivieren"
L["Enabled"] = "Aktiviert"
L["Menu"] = "Menü"
L["Context Menu"] = "Kontextmenü"
L["Left Click"] = "Linksklick"
L["Drag"] = "Ziehen"
L["Available"] = "Verfügbar"
L["Unavailable"] = "Nicht verfügbar"
L["Collapsed"] = "Eingeklappt"
L["Expanded"] = "Ausgeklappt"
L["Expand/Collapse"] = "Aus-/Einklappen"
L["Known"] = "Bekannt"
L["Search"] = "Suchen"
L["Clear"] = "Löschen"
L["Results"] = "Ergebnisse"
L["Categories"] = "Kategorien"
L["Page"] = "Seite"
L["Previous Page"] = "Vorherige Seite"
L["Next Page"] = "Nächste Seite"
L["Add"] = "Hinzufügen"
L["Remove"] = "Entfernen"
L["Unlearn"] = "Verlernen"

L["Empty"] = "Leer"
L["None"] = "Keine"
L["Type"] = "Typ"
L["Select Type"] = "Typ auswählen"
L["Power Type"] = "Krafttyp"
L["Unit"] = "Einheit"
L["Instance ID"] = "Instanz-ID"
L["Parameters"] = "Parameter"
L["Items"] = "Gegenstände"
L["Options"] = "Optionen"
L["Scroll Up"] = "Nach oben scrollen"
L["Scroll Down"] = "Nach unten scrollen"
L["Minimum"] = "Minimum"
L["Maximum"] = "Maximum"
L["in stock"] = "auf Lager"
L["Gold"] = "Gold"
L["Silver"] = "Silber"
L["Copper"] = "Kupfer"
L["Price"] = "Preis"
L["Quantity"] = "Menge"
L["Place Item Here"] = "Gegenstand hier platzieren"
L["Repair"] = "Reparieren"
L["Replace"] = "Ersetzen"
L["Replace?"] = "Ersetzen?"
L["Voice Pack"] = "Stimmenpaket"
L["Socketing"] = "Sockelung"
L["Interact"] = "Interagieren"
L["Close"] = "Schließen"
L["Goodbye"] = "Auf Wiedersehen"
L["Available Quest"] = "Verfügbare Quest"
L["Accepted Quest"] = "Angenommene Quest"
L["Details"] = "Details"
L["Progress"] = "Fortschritt"
L["Rewards"] = "Belohnungen"

L["Objectives"] = "Ziele"
L["Complete"] = "Abgeschlossen"
L["Failed"] = "Fehlgeschlagen"

L["Spells"] = "Zauber"
L["Spell Flyout"] = "Zauberauswahl"
L["Enchant"] = "Verzauberung"
L["Trade"] = "Handel"

--Colors
L["Red"] = "Rot"
L["Orange"] = "Orange"
L["Yellow"] = "Gelb"
L["Green"] = "Grün"
L["Blue"] = "Blau"
L["Grey"] = "Grau"
L["Meta"] = "Meta"
L["Prismatic"] = "Prismatisch"
L["Reward"] = "Belohnung"

--Character frame
L["Equipment"] = "Ausrüstung"
L["Stats"] = "Werte"
L["Resistances"] = "Widerstände"
L["Mounted"] = "Aufgesessen"

--Equipment slot names (for empty slots)
L["Ammo"] = "Munition"
L["Head"] = "Kopf"
L["Neck"] = "Hals"
L["Shoulders"] = "Schultern"
L["Back"] = "Rücken"
L["Chest"] = "Brust"
L["Shirt"] = "Hemd"
L["Tabard"] = "Wappenrock"
L["Wrist"] = "Handgelenke"
L["Hands"] = "Hände"
L["Waist"] = "Taille"
L["Legs"] = "Beine"
L["Feet"] = "Füße"
L["Finger"] = "Finger"
L["Trinket"] = "Schmuck"
L["Main Hand"] = "Haupthand"
L["Off Hand"] = "Nebenhand"
L["Ranged"] = "Distanz"

--Talents
L["Talents"] = "Talente"
L["Specializations"] = "Spezialisierungen"
L["Specialization Info"] = "Spezialisierungsinfo"
L["Glyphs"] = "Glyphen"

--Object field labels
L["Current"] = "Aktuell"
L["Label"] = "Bezeichnung"
L["Percent"] = "Prozent"
L["Formatted"] = "Formatiert"
L["Active"] = "Aktiv"
L["Status"] = "Status"
L["Name"] = "Name"

--Aura field labels
L["Applications"] = "Anwendungen"
L["Aura Instance ID"] = "Aura-Instanz-ID"
L["Can Apply Aura"] = "Kann Aura anwenden"
L["Charges"] = "Aufladungen"
L["Dispel Type"] = "Bannart"
L["Curse"] = "Fluch"
L["Disease"] = "Krankheit"
L["Magic"] = "Magie"
L["Poison"] = "Gift"
L["Enrage"] = "Raserei"
L["Duration"] = "Dauer"
L["Expiration Time"] = "Ablaufzeit"
L["Remaining Duration"] = "Verbleibende Dauer"
L["Icon"] = "Symbol"
L["Is Boss Aura"] = "Ist Boss-Aura"
L["Is From Player Or Pet"] = "Ist vom Spieler oder Begleiter"
L["Is Harmful"] = "Ist schädlich"
L["Is Helpful"] = "Ist hilfreich"
L["Is Nameplate Only"] = "Nur auf Namensplakette"
L["Is Raid"] = "Ist Schlachtzug"
L["Is Stealable"] = "Ist stehlbar"
L["Max Charges"] = "Maximale Aufladungen"
L["Nameplate Show All"] = "Namensplakette alle anzeigen"
L["Nameplate Show Personal"] = "Namensplakette eigene anzeigen"
L["Points"] = "Punkte"
L["Source Unit"] = "Quelleinheit"
L["Spell ID"] = "Zauber-ID"
L["Time Mod"] = "Zeitmodifikator"

--Buffer labels
L["Objects"] = "Objekte"
L["Object"] = "Objekt"
L["Source"] = "Quelle"
L["New Buffer"] = "Neuer Puffer"
L["New"] = "Neu"
L["Select Buffer Type"] = "Puffertyp auswählen"
L["Buffer Not Found"] = "Puffer nicht gefunden"
L["Buffer Group"] = "Puffergruppe"
L["No object configured"] = "Kein Objekt konfiguriert"
L["Empty Object"] = "Leeres Objekt"
L["Template"] = "Vorlage"
L["Custom"] = "Benutzerdefiniert"
L["Format"] = "Format"
L["Default"] = "Standard"
L["Save"] = "Speichern"
L["Invalid parameters"] = "Ungültige Parameter"
L["Parameters must identify a single object"] = "Parameter müssen ein einzelnes Objekt identifizieren"

--Time
L["day"] = "Tag"
L["days"] = "Tage"
L["hour"] = "Stunde"
L["hours"] = "Stunden"
L["minute"] = "Minute"
L["minutes"] = "Minuten"
L["second"] = "Sekunde"
L["seconds"] = "Sekunden"
L["Number"] = "Zahl"
