local L = WowVision:translate("enUS")

L["Auction House"] = true
L["Auctions"] = true
L["Buyout Frame"] = true
L["Bid Frame"] = true

L["Ascending"] = true
L["Descending"] = true
L["Sort Column"] = true

L["Filters"] = true
L["Unit Price"] = true
L["Starting Bid"] = true
L["Buyout Price"] = true
L["No Bids"] = true
L["Bid Price"] = true
L["Seller"] = true
L["Sold"] = true
L["Bids"] = true
L["Bid Amount"] = true
L["Minimum Bid"] = true
L["Bidder"] = true
L["Time Left"] = true
L["Short"] = true
L["Medium"] = true
L["Long"] = true
L["Very Long"] = true

L["Min Stack Size"] = true
L["No Results"] = true

-- AH scanner / price database (PRs 9-11)
L["Scan"] = true
L["Scanning"] = true
L["Scan Results"] = true
L["Scan complete"] = true
L["Scan aborted"] = true
L["Scan failed"] = true
L["Abort Scan"] = true
L["Auto Scan"] = true
L["Full Scan"] = true
L["Full scan started"] = true
L["Full scan complete"] = true
L["Full scan aborted"] = true
L["Full scan failed"] = true
L["Load More"] = true
L["scanned"] = true
L["auctions"] = true
L["items updated"] = true
L["Auction Price"] = true
L["Auction Prices"] = true
L["Tooltip Prices"] = true
L["Price Options"] = true
L["Vendor Buy"] = true
L["Vendor Sell"] = true
L["Day Mean"] = true
L["Mean Days"] = true
L["History Days"] = true
L["days ago"] = true
L["Auction not open"] = true
L["Cooldown active"] = true
L["Item not found"] = true
L["Item purchased"] = true
L["12 Hours"] = true
L["24 Hours"] = true
L["48 Hours"] = true
L["Buyout"] = true
L["Current Bid"] = true
L["Stack Size"] = true
L["Number of Stacks"] = true
L["Deposit"] = true
L["Minimum Level"] = true
L["Maximum Level"] = true
L["Sort"] = true
L["Selected"] = true
L["Create Auction"] = true
L["Item Selected"] = true
