local L = WowVision:translate("enUS")

-- Minimap scanner (core/minimap)
L["Minimap Scanner"] = true
L["Scan Minimap"] = true
L["Announce Tracked Dots While Walking"] = true
L["Switch Gathering Tracking Off To Sort Nodes"] = true
L["Centre Mouse Cursor Before Scanning"] = true
L["New Minimap Dot Alert"] = true
L["Other NPCs"] = true
L["Unsorted"] = true
L["Gathering"] = true
L["quest giver"] = true
L["quest available"] = true
L["turn in"] = true
L["low level"] = true
L["Scanning minimap"] = true
L["Scan done"] = true
L["new"] = true
L["gone"] = true
L["Nothing new nearby"] = true
L["Scan already running"] = true
L["Minimap scanner not available on this client"] = true
L["Not in combat"] = true
L["Stand still to scan"] = true
L["Stop mouselook to scan"] = true
L["No position here"] = true
L["Minimap scan failed"] = true
L["Tracking not restored"] = true
L["Seen entries cleared"] = true
L["indoors, this building only"] = true
L["Scan canceled"] = true
L["moved"] = true
L["turned"] = true
L["combat"] = true
L["mouse"] = true
L["mouselook"] = true
L["window"] = true
L["Turn on friendly NPC nameplates to learn NPC names"] = true
L["Points of Interest"] = true
L["Tracking"] = true
L["Minimap Tracking"] = true
L["Map Filter"] = true
