local L = WowVision:translate("enUS")

L["alternate"] = true
L["alternate encounter"] = true
L["alternate mount"] = true
L["alternate quest"] = true
L["arcane charges"] = true
L["balance"] = true
L["burning embers"] = true
L["chi"] = true
L["combo points"] = true
L["demonic fury"] = true
L["energy"] = true
L["essence"] = true
L["focus"] = true
L["fury"] = true
L["happiness"] = true
L["holy power"] = true
L["insanity"] = true
L["lunar power"] = true
L["maelstrom"] = true
L["mana"] = true
L["pain"] = true
L["rage"] = true
L["blood runes"] = true
L["death runes"] = true
L["frost runes"] = true
L["unholy runes"] = true
L["runes"] = true
L["runic power"] = true
L["shadow orbs"] = true
L["soul shards"] = true